### PR TITLE
Familiarization Project_Direct Messages

### PR DESCRIPTION
**Pull request by stanleynwakamma**
This is a new PR for the implemented changes to the message.java file. Please ignore the index.html part; I never knew it will still appear in this new PR.

### CODE REVIEW

**Comment by kyrabusser** [comment]
Nice work, Stanley!

What happens when you run `mvn appengine:devserver` with this version? Do you see any errors? We want to make sure that the version of the code in master always compiles and runs correctly, so it's good to check this.

It looks like the change to index.html is from your "Just testing" commit, right? If you want to undo that change, you can use `git revert`:
 - First find the commit hash, using `git log` and looking for the long string after "commit". I highlighted the commit in this screenshot: 
image (You can also see the commit hash here in GitHub, yours starts with "11f1520")

- Next, run `git revert [put the long commit hash here]`. That will make a _new_ commit that undoes the original change.

- Finally, run `git push` so we can see the undo here in GitHub.

That's a lot of work to undo just a couple of lines, but it's a handy tool to know (and it will get rid of the "This branch has conflicts that must be resolved" warning that won't let you merge). Here's a GitHub blog post that has a *lot* more examples of ways to undo all kinds of different things: https://github.blog/2015-06-08-how-to-undo-almost-anything-with-git/

Great work sticking with this and learning more about Git! :smile:

**Review by kyrabusser — COMMENTED** [review]
Nice work, Stanley!

Can you please update your PR title (there's an edit button next to it) now that you're changing more than just the Message.java file?

Can you also confirm that you've tested this locally with `mvn appengine:devserver` and that all of the existing functionality (sending messages, looking at the /feed url) works correctly? Is there any new behavior we should notice if we run this change?

**Comment by stanleynwakamma** [comment]
@kyrabusser Thank you for your continued guidance! Yes I tested the code locally with ### `mvn appengine:devserver` and it runs correctly according to the steps 1 - 4 of the familiarization project. The existing functionality which includes sending messages and looking at the feed works correctly. 
Some new functionality we should notice when we run this code include the addition of a query parameter to the POST requests that are sent when a user submits a message. But the behavior remains basically the same as it was originally coded.

**Comment by stanleynwakamma** [comment]
@kyrabusser @CharlesArday @hengelman Please can someone review this pull request and merge with the master? 
I'm working to finish the remaining steps of my familiriazation project. @CharlesArday Please notify me when working on `showMessageFormIfViewingSelf()` so we don't break each other's code. 
Thanks everyone!

**Review by kyrabusser — APPROVED** [review]
Thanks so much for updating with the results of your testing, Stanley! :+1: 

I'll let you handle the merge into master--let me know if you have any questions!

**Pull request merged**
